HMRC-814: Adds tag-production action
This is needed to avoid rotating production images and blocking future
rollbacks in the ECS UI since the image would need rebuilding and
pushing

Co-authored-by: Aigul Djon <aigul.djon@gmail.com>

diff --git a/.github/actions/tag-production/action.yml b/.github/actions/tag-production/action.yml
--- a/.github/actions/tag-production/action.yml
+++ b/.github/actions/tag-production/action.yml
@@ -26,27 +26,29 @@ runs:
         echo RESOLVED_REF=$(git rev-parse --short "$REF") >> "$GITHUB_OUTPUT"
       shell: bash
     - run: |
-        # Extract repository name and registry id from ecr-url (assumes format: <account>.dkr.ecr.<region>.amazonaws.com/<repo>)
         REPO_NAME=$(echo "${{ inputs.ecr-url }}" | cut -d'/' -f2)
-        REGISTRY_ID=$(echo "${{ inputs.ecr-url }}" | cut -d'.' -f1)
         REF=${{ steps.resolved-ref.outputs.RESOLVED_REF }}
-        IMAGE_NAME="${{ inputs.ecr-url }}:$REF"
+        EXISTING_IMAGE_NAME="${{ inputs.ecr-url }}:$REF"
 
         aws ecr get-login-password --region ${{ inputs.region }} \
           | docker login --username AWS --password-stdin "${{ inputs.ecr-url }}"
 
         if aws ecr describe-images \
-          --repository "$REPO_NAME" \
+          --repository-name "$REPO_NAME" \
           --image-ids imageTag="$REF" \
           --region "${{ inputs.region }}" \
-          --registry-id "$REGISTRY_ID" > /dev/null 2>&1; then
-          echo "::notice::Image $IMAGE_NAME already exists in ECR. Skipping build and push."
-          exit 0
+          > /dev/null 2>&1; then
+          echo "::notice::Image $EXISTING_IMAGE_NAME already exists in ECR. Creating a tag for this release.
         else
-          echo "::notice::Image $IMAGE_NAME not found in ECR. Proceeding with build and push."
+          echo "::error::Image $EXISTING_IMAGE_NAME not found in ECR. Fatal skipping tagging"
+          exit 1
         fi
 
-        echo "$REF" > REVISION
-        docker build -t "$IMAGE_NAME" .
-        docker push "$IMAGE_NAME"
+        RELEASE_IMAGE_NAME="${{ inputs.ecr-url }}:$(release-$(date +"%Y%m%d-%H%M"))"
+
+        docker pull $EXISTING_IMAGE_NAME
+        docker tag $EXISTING_IMAGE_NAME $RELEASE_IMAGE_NAME
+        docker push $RELEASE_IMAGE_NAME
+
+        echo "::notice::Successfully built and pushed $RELEASE_IMAGE_NAME"
       shell: bash
