Add docker deployment support to CI DEV

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,3 +1,4 @@
+---
 version: 2.1
 
 orbs:
@@ -40,20 +41,96 @@ commands:
           name: "Push new app in dark mode"
           command: |
             export BUILDPACK="https://github.com/cloudfoundry/ruby-buildpack.git#<< parameters.buildpack_version >>"
-
             # Enables /healthcheck to show the current deployed git sha
             export GIT_NEW_REVISION=$(git rev-parse --short HEAD)
             echo $GIT_NEW_REVISION >REVISION
-
             # Push as "dark" instance
             cf push "$CF_APP-<< parameters.environment_key >>-dark" -f deploy_manifest.yml --no-route --buildpack $BUILDPACK
-
             # Map dark route
             cf map-route  "$CF_APP-<< parameters.environment_key >>-dark" london.cloudapps.digital -n "$CF_APP-<< parameters.environment_key >>-dark"
-
             # Enable routing from this service to the backend applications which are private
             cf add-network-policy "$CF_APP-<< parameters.environment_key >>-dark" "$CF_BACKEND_APP_XI-<< parameters.environment_key >>" --protocol tcp --port 8080
             cf add-network-policy "$CF_APP-<< parameters.environment_key >>-dark" "$CF_BACKEND_APP_UK-<< parameters.environment_key >>"  --protocol tcp --port 8080
+      - run:
+          name: "Verify new version is working on dark URL."
+          command: |
+            sleep 15
+            # Verify new version is working on dark URL.
+            HTTPCODE=`curl -s -o /dev/null -w "%{http_code}" https://$CF_APP-<< parameters.environment_key >>-dark.london.cloudapps.digital/duty-calculator/ping`
+            if [ "$HTTPCODE" -ne 200 ];then
+              echo "dark route not available, failing deploy ($HTTPCODE)"
+              cf logs "$CF_APP-<< parameters.environment_key >>-dark" --recent
+              cf delete -f  "$CF_APP-<< parameters.environment_key >>-dark"
+              exit 1
+            fi
+      - run:
+          name: "Switch dark app to live"
+          command: |
+            # Send "real" url to new version
+            cf unmap-route "$CF_APP-<< parameters.environment_key >>-dark" london.cloudapps.digital -n "$CF_APP-<< parameters.environment_key >>-dark"
+            # Start sending traffic to new version
+            cf map-route  "$CF_APP-<< parameters.environment_key >>-dark" london.cloudapps.digital -n "$CF_APP-<< parameters.environment_key >>"
+            # TODO: Update when we remove referring service from the path
+            cf map-route  "$CF_APP-<< parameters.environment_key >>-dark" "<< parameters.app_domain_prefix >>".trade-tariff.service.gov.uk --path "/duty-calculator"
+            # Stop sending traffic to previous version
+            cf unmap-route  "$CF_APP-<< parameters.environment_key >>" london.cloudapps.digital -n "$CF_APP-<< parameters.environment_key >>"
+            cf unmap-route  "$CF_APP-<< parameters.environment_key >>" "<< parameters.app_domain_prefix >>".trade-tariff.service.gov.uk --path "/duty-calculator"
+            # stop previous version
+            cf stop "$CF_APP-<< parameters.environment_key >>"
+            # delete previous version
+            cf delete "$CF_APP-<< parameters.environment_key >>" -f
+            # Switch name of "dark" version to claim correct name
+            cf rename "$CF_APP-<< parameters.environment_key >>-dark" "$CF_APP-<< parameters.environment_key >>"
+      - slack/notify:
+          channel: deployments
+          event: fail
+          template: basic_fail_1
+      - slack/notify:
+          channel: deployments
+          event: pass
+          template: basic_success_1
+
+  cf_deploy_docker:
+    parameters:
+      space:
+        type: string
+      environment_key:
+        type: string
+      app_domain_prefix:
+        type: string
+      buildpack_version:
+        type: string
+        default: "v1.8.39"
+    steps:
+      - checkout
+      - run:
+          name: "Setup CF CLI"
+          command: |
+            curl -L -o cf.deb 'https://packages.cloudfoundry.org/stable?release=debian64&version=7.2.0&source=github-rel'
+            sudo dpkg -i cf.deb
+            cf -v
+            cf api "$CF_ENDPOINT"
+            cf auth "$CF_USER" "$CF_PASSWORD"
+            cf add-plugin-repo CF-Community https://plugins.cloudfoundry.org
+            cf install-plugin app-autoscaler-plugin -r CF-Community -f
+            cf target -o "$CF_ORG" -s "<< parameters.space >>"
+      - run:
+          name: "Fetch existing manifest"
+          command: |
+            cf create-app-manifest "$CF_APP-<< parameters.environment_key >>" -p deploy_manifest.yml
+      - run:
+          name: "Push new app in dark mode"
+          command: |
+            export IMAGE=enginetransformation/tariff-dutycalculator
+            export DOCKER_IMAGE=${IMAGE}:dev-${CIRCLE_SHA1}
+
+            # Push as "dark" instance
+            cf push "$CF_APP-<< parameters.environment_key >>-dark" -f deploy_manifest.yml --no-route --docker-image "$DOCKER_IMAGE"
+            # Map dark route
+            cf map-route  "$CF_APP-<< parameters.environment_key >>-dark" london.cloudapps.digital -n "$CF_APP-<< parameters.environment_key >>-dark"
+            # Enable routing from this service to the backend applications which are private
+            cf add-network-policy "$CF_APP-<< parameters.environment_key >>-dark" "$CF_BACKEND_APP_XI-<< parameters.environment_key >>" --protocol tcp --port 8080
+            cf add-network-policy "$CF_APP-<< parameters.environment_key >>-dark" "$CF_BACKEND_APP_UK-<< parameters.environment_key >>" --protocol tcp --port 8080
       - run:
           name: "Verify new version is working on dark URL."
           command: |
@@ -131,9 +208,14 @@ jobs:
           command:  bundle exec brakeman -o brakeman_results.html
       - store_artifacts:
           path: brakeman_results.html
+
   build:
     environment:
       IMAGE_NAME: enginetransformation/tariff-dutycalculator
+    parameters:
+      dev-build:
+        default: false
+        type: boolean
     docker:
       - image: cimg/ruby:2.7.3-node
     steps:
@@ -144,12 +226,12 @@ jobs:
       - run:
           name: "Build Docker image"
           command: |
-            docker build -t $IMAGE_NAME:${CIRCLE_SHA1} .
+            docker build -t $IMAGE_NAME:<<# parameters.dev-build >>dev-<</ parameters.dev-build >>${CIRCLE_SHA1} .
       - run:
           name: "Push image"
           command: |
             echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
-            docker push $IMAGE_NAME:${CIRCLE_SHA1}
+            docker push $IMAGE_NAME:<<# parameters.dev-build >>dev-<</ parameters.dev-build >>${CIRCLE_SHA1}
 
   test:
     docker:
@@ -190,7 +272,7 @@ jobs:
     environment:
       SENTRY_ENVIRONMENT: "development"
     steps:
-      - cf_deploy:
+      - cf_deploy_docker:
           space: "development"
           environment_key: "dev"
           app_domain_prefix: "dev"
@@ -233,6 +315,7 @@ workflows:
                 - master
       - build:
           context: trade-tariff
+          dev-build: true
           requires:
             - test
       - deploy_dev:
@@ -242,7 +325,7 @@ workflows:
               ignore:
                 - master
           requires:
-            - test
+            - build
       - deploy_staging:
           context: trade-tariff
           filters:
