Tweaks to ci process

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -40,17 +40,17 @@ commands:
 
             # Enable routing from this frontend to backend applications which are private
             cf add-network-policy "$CF_APP-<< parameters.domain_prefix >>-dark" "$CF_BACKEND_APP_XI-<< parameters.domain_prefix >>" --protocol tcp --port 8080
-#      - run:
-#          name: "Verify new version is working on dark URL."
-#          command: |
-#            sleep 15
-#            # TODO: Retry
-#            # Verify new version is working on dark URL.
-#            HTTPCODE=`curl -s -o /dev/null -w "%{http_code}" https://$CF_APP-<< parameters.domain_prefix >>-dark.london.cloudapps.digital/healthcheck`
-#            if [ "$HTTPCODE" -ne 200 ];then
-#              echo "dark route not available, failing deploy ($HTTPCODE)"
-#              exit 1
-#            fi
+      - run:
+          name: "Verify new version is working on dark URL."
+          command: |
+            sleep 15
+            # Verify new version is working on dark URL.
+            HTTPCODE=`curl -s -o /dev/null -w "%{http_code}" https://$CF_APP-<< parameters.domain_prefix >>-dark.london.cloudapps.digital/ping`
+
+            if [ "$HTTPCODE" -ne 200 ];then
+              echo "dark route not available, failing deploy ($HTTPCODE)"
+              exit 1
+            fi
       - run:
           name: "Switch dark app to live"
           command: |
@@ -71,28 +71,19 @@ commands:
             #cf delete "$CF_APP-<< parameters.domain_prefix >>" -f
 
             # Switch name of "dark" version to claim correct name
-            #cf rename "$CF_APP-<< parameters.domain_prefix >>-dark" "$CF_APP-<< parameters.domain_prefix >>"
-#      - slack/notify:
-#          channel: deployments
-#          event: fail
-#          template: basic_fail_1
-#      - slack/notify:
-#          channel: deployments
-#          event: pass
-#          template: basic_success_1
+            cf rename "$CF_APP-<< parameters.domain_prefix >>-dark" "$CF_APP-<< parameters.domain_prefix >>"
+      - slack/notify:
+          channel: deployments
+          event: fail
+          template: basic_fail_1
+      - slack/notify:
+          channel: deployments
+          event: pass
+          template: basic_success_1
 
 
 
 jobs:
-  build:
-    docker:
-      - image: cimg/ruby:2.7-node
-    steps:
-      - checkout
-      - ruby/install-deps
-      - node/install-packages:
-          pkg-manager: yarn
-          cache-key: "yarn.lock"
   checking:
     docker:
       - image: 'cimg/ruby:2.7-node'
@@ -117,6 +108,12 @@ jobs:
           pkg-manager: yarn
           cache-key: "yarn.lock"
       - ruby/rspec-test
+      - store_artifacts:
+          path: coverage
+      - slack/notify:
+          channel: deployments
+          event: fail
+          template: basic_fail_1
   deploy_dev:
     docker:
       - image: cimg/ruby:2.7
@@ -129,18 +126,17 @@ workflows:
   version: 2
   build_and_test:
     jobs:
-#      - build
-#      - checking
-#      - test:
-#          requires:
-#            - build
+      - checking
+      - test:
+          filters:
+            branches:
+              ignore:
+                - master
       - deploy_dev:
           context: trade-tariff
- #     - cloudfoundry/push:
- #         requires:
- #           - test
- #         appname: tariff-duty-calculator-dev
- #         endpoint: api.london.cloud.service.gov.uk
- #         org: trade-tariff
- #         space: development
- #         manifest: manifest.yml
+          filters:
+            branches:
+              ignore:
+                - master
+          requires: 
+            - test
